--TOTAL DE EMPRESAS
SELECT COUNT(DISTINCT ID) AS TOTAL_CLIENTES FROM CLIENTE;

--TOTAL EMPRESAS EM Declínio
SELECT COUNT(DISTINCT ID) AS TOTAL_DECLINIO FROM CLIENTE WHERE CLASSIFICACAO = 'Declínio'

--TIPO DE TRANSACAO MAIS UTILIZADO 
SELECT TOP 1 DS_TRAN AS DESCRICAO, COUNT(*) AS QUANTIDADE
FROM FATURAMENTO
GROUP BY DS_TRAN
ORDER BY QUANTIDADE DESC;

--LEVANTAMENTO Quantidade x Classificação de Perfil
SELECT 
  CLASSIFICACAO,
  COUNT(DISTINCT ID) AS QTD_CLIENTES,
  CAST(
    ROUND(
      COUNT(DISTINCT ID) * 100.0 / 
      (SELECT COUNT(DISTINCT ID) FROM CLIENTE WHERE CLASSIFICACAO IS NOT NULL), 2) AS DECIMAL(5,2)) AS PORCENTAGEM
FROM CLIENTE
WHERE CLASSIFICACAO IS NOT NULL
GROUP BY CLASSIFICACAO
ORDER BY PORCENTAGEM DESC;

--LEVANTAMENTO Valor Transacionado por Tipo
SELECT DS_TRAN AS TIPO_TRANSACAO, SUM(VL) AS TOTAL_TRANSACAO_TIPO FROM FATURAMENTO
GROUP BY DS_TRAN
ORDER BY TOTAL_TRANSACAO_TIPO DESC;

--SELECT TOP 10 EMPRESAS DA PESQUISA DIRETO NO FRONT
SELECT TOP 10 *
FROM (
  SELECT DISTINCT ID, DS_CNAE AS CNAE
  FROM CLIENTE
  WHERE ID LIKE '%%'
    AND LOWER(CLASSIFICACAO) LIKE '%%'
) AS SUB;

