use CHALLENGE

declare @ID VARCHAR(255)
declare @cnae varchar(50)
SET @ID = 'CNPJ_00002'

--SELECT 1 NAME AND CNPJ HEADER
SELECT distinct
	-- NOME,
	ID  FROM CLIENTE 
WHERE ID = @ID

SELECT @cnae =  DS_CNAE FROM CLIENTE WHERE ID = @ID
-- SELECT 2 DADOS BASICOS
SELECT DISTINCT
  C.ID,
  S.SALDO_TOTAL_CLIENTE AS SALDO,
    CAST(
    (
      SELECT 
        SUM(
          TRY_CAST(REPLACE(REPLACE(LTRIM(RTRIM(FC.SALDO_MES)), '+', ''), ',', '') AS DECIMAL(18,2))
        ) / COUNT(*)
      FROM FATURAMENTO_CLIENTE FC
      WHERE FC.CLIENTE = C.ID
    ) AS DECIMAL(18,2)
  ) AS MEDIA, -- CAMPO 2
  C.CLASSIFICACAO, --CAMPO 3
  C.DS_CNAE AS RAMO -- CAMPO 4
FROM CLIENTE C
JOIN SALDO_CLIENTE S ON C.ID = CLIENTE
WHERE C.ID = @ID
GROUP BY C.ID, C.CLASSIFICACAO, C.DS_CNAE, S.SALDO_TOTAL_CLIENTE

-- SELECT 3 ACOMPANHAMENTO
SELECT CLIENTE, MES_REFERENCIA AS MES, SALDO_MES AS SALDO  FROM FATURAMENTO_CLIENTE WHERE CLIENTE = @ID

-- SELECT 4 PRINCIPAIS RELACIONAMENTOS PAGADORES
SELECT 
  R.PARCEIRO,
  SUM(R.ENTRADA) AS TOTAL_ENTRADA,
  SUM(R.SAIDA) AS TOTAL_SAIDA,
  COUNT(*) AS INTERACOES
FROM (
  -- Saída: CNPJ_06663 pagou para PARCEIRO
  SELECT 
    F.ID_RCBE AS PARCEIRO,
    0 AS ENTRADA,
    TRY_CAST(REPLACE(CAST(F.VL AS VARCHAR), ',', '') AS DECIMAL(18,2)) AS SAIDA
  FROM FATURAMENTO F
  WHERE F.ID_PGTO = @ID

  UNION ALL

  -- Entrada: PARCEIRO pagou para CNPJ_06663
  SELECT 
    F.ID_PGTO AS PARCEIRO,
    TRY_CAST(REPLACE(CAST(F.VL AS VARCHAR), ',', '') AS DECIMAL(18,2)) AS ENTRADA,
    0 AS SAIDA
  FROM FATURAMENTO F
  WHERE F.ID_RCBE = @ID
) R
GROUP BY R.PARCEIRO
ORDER BY INTERACOES DESC, TOTAL_SAIDA DESC

-- SELECT 5 PRINCIPAIS RELACIONAMENTOS RECEBEDORES
SELECT TOP 5
  R.PARCEIRO,
  SUM(R.ENTRADA) AS TOTAL_ENTRADA,
  SUM(R.SAIDA) AS TOTAL_SAIDA,
  COUNT(*) AS INTERACOES
FROM (
  -- Saída: CNPJ_06663 pagou para PARCEIRO
  SELECT 
    F.ID_RCBE AS PARCEIRO,
    0 AS ENTRADA,
    TRY_CAST(REPLACE(CAST(F.VL AS VARCHAR), ',', '') AS DECIMAL(18,2)) AS SAIDA
  FROM FATURAMENTO F
  WHERE F.ID_PGTO = @ID

  UNION ALL

  -- Entrada: PARCEIRO pagou para CNPJ_06663
  SELECT 
    F.ID_PGTO AS PARCEIRO,
    TRY_CAST(REPLACE(CAST(F.VL AS VARCHAR), ',', '') AS DECIMAL(18,2)) AS ENTRADA,
    0 AS SAIDA
  FROM FATURAMENTO F
  WHERE F.ID_RCBE = @ID
) R
GROUP BY R.PARCEIRO
ORDER BY INTERACOES DESC, TOTAL_ENTRADA DESC


-- SELECT 6 EMPRESAS SEMELHANTES
SELECT DISTINCT ID, DS_CNAE, CLASSIFICACAO  FROM CLIENTE where DS_CNAE = @cnae

