CREATE VIEW CARGA_CLASSIFICATION AS
SELECT    
  C.ID AS CLIENTE,    
  C.DT_ABRT,    
  SUM(FC.SALDO_MES) AS SALDO_TOTAL_CLIENTE    
FROM CLIENTE C    
LEFT JOIN FATURAMENTO_CLIENTE FC ON FC.CLIENTE = C.ID    
WHERE C.CLASSIFICACAO IS NULL or c.CLASSIFICACAO = 'Não Classificado'  /* Se quiser filtrar só os não classificados */    
GROUP BY C.ID, C.DT_ABRT; 