CREATE VIEW SALDO_CLIENTE AS
	SELECT
	  CLIENTE, DT_ABRT,
	  SUM(
		CASE 
		  WHEN SALDO_MES IS NULL THEN 0.00
		  WHEN LEFT(LTRIM(RTRIM(SALDO_MES)), 1) = '-' THEN 
			TRY_CAST(REPLACE(SUBSTRING(LTRIM(RTRIM(SALDO_MES)), 2, LEN(LTRIM(RTRIM(SALDO_MES)))), ',', '') AS DECIMAL(18,2)) * -1
		  WHEN LEFT(LTRIM(RTRIM(SALDO_MES)), 1) = '+' THEN 
			TRY_CAST(REPLACE(SUBSTRING(LTRIM(RTRIM(SALDO_MES)), 2, LEN(LTRIM(RTRIM(SALDO_MES)))), ',', '') AS DECIMAL(18,2))
		  ELSE 
			TRY_CAST(REPLACE(LTRIM(RTRIM(SALDO_MES)), ',', '') AS DECIMAL(18,2))
		END
	  ) AS SALDO_TOTAL_MENSAL
	FROM VW_FATURAMENTO_CLIENTE
	JOIN CLIENTE ON ID = CLIENTE
	GROUP BY CLIENTE, DT_ABRT