ALTER VIEW SALDO_CLIENTE AS
WITH CLIENTE_SUB AS (
    SELECT *
    FROM (
        SELECT 
            C.*,
            ROW_NUMBER() OVER (PARTITION BY C.ID ORDER BY C.ID) AS RN
        FROM CLIENTE C
    ) AS Sub
    WHERE RN = 1
)
SELECT
    C.ID AS CLIENTE,
    C.DT_ABRT,
    SUM(FC.SALDO_MES) AS SALDO_TOTAL_CLIENTE
FROM CLIENTE_SUB C
LEFT JOIN FATURAMENTO_CLIENTE FC ON FC.CLIENTE = C.ID
GROUP BY C.ID, C.DT_ABRT;