CREATE TABLE FATURAMENTO(
ID_PGTO VARCHAR(50) NOT NULL,	
ID_RCBE VARCHAR(50) NOT NULL,
VL FLOAT DEFAULT 0.0,
DS_TRAN VARCHAR(50),
DT_REFE SMALLDATETIME
)
CREATE INDEX IX_FATURAMENTO_ID_PGTO ON FATURAMENTO(ID_PGTO);
CREATE INDEX IX_FATURAMENTO_ID_RCBE ON FATURAMENTO(ID_RCBE);
CREATE INDEX IX_FATURAMENTO_DT_REFE ON FATURAMENTO(DT_REFE);

-- Tabela temporária para consumir a base em .csv
CREATE TABLE FATURAMENTO_TEMP (
    ID_PGTO VARCHAR(50) NOT NULL,	
	ID_RCBE VARCHAR(50) NOT NULL,
	VL FLOAT DEFAULT 0.0,
	DS_TRAN VARCHAR(50),
	DT_REFE VARCHAR(20)
);

-- BULK INSERT processo util para SQL SERVER (Não sei se funciona para outros bancos, só usei no SSMS)
BULK INSERT FATURAMENTO_TEMP
FROM 'C:\Users\osval\Downloads\base2 (1).csv'
	WITH (
		CODEPAGE = '65001',         -- UTF-8
		FIELDTERMINATOR = ';',      -- Separador de campos (ex: vírgula)
		ROWTERMINATOR = '\n',       -- Separador de linhas
		FIRSTROW = 2                -- Ignora o cabeçalho, se houver
	);

INSERT INTO FATURAMENTO (ID_PGTO, ID_RCBE, VL, DS_TRAN, DT_REFE)
SELECT
    ID_PGTO,
    ID_RCBE,
    VL,
    DS_TRAN,
    CONVERT(SMALLDATETIME, DT_REFE, 103)
FROM FATURAMENTO_TEMP;